version: '3'
services:
  playground:
    container_name: 'GymTestContainer'
    hostname: 'GymTestContainer'
    build: .
    restart: always
    working_dir: '/workspace'
    tty: true
    volumes:
      - type: bind
        source: ..
        target: /workspace
